### ISSUE TITLE
Magicchatbox not showing any sort of interaction with vrchat (Solved)

### ISSUE THREAD

**Issue by DarlingServant** [BoiHanny/vrcosc-magicchatbox#58]
CMD prompt shows that i have Dotnet 8 installed correctly as a runtime alongside OSC being enabled within vrchat:

C:\Windows\System32>dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
...
...
...
...
... (other runtimes were listed here such as 6.0 a bunch...)

yet, it seems that magicchatbox has 0 interaction with vrchat even whilst on other ports and not 9000 and on desktop mode to avoid maybe my SlimeVR program from interfering. the program had previously worked but maybe a vrchat or chatbox update and suddenly, it stopped working a few months back. 

is it something to do with the "local ip" and changing that to one listed by command prompt?
is it a vrchat thing, such as "install.exe" as ive been told apparently breaks OSC working?
please help! i really enjoyed using this program as a way of communication with others and would like to go back to that experience!

**Comment by DarlingServant** [comment]
Fixed, my issue was my listed IP was 192.0.0.1 instead of 127.0.0.1

**Comment by StefanoMexicano** [comment]
Im experiencing this same problem and i have no idea how to fix it. It just stopped working yesterday and i even tried redownloading it but it still doesnt work.
